import { beforeEach, describe, expect, it, vi } from 'vitest'
import { createPinia } from 'pinia'
import { reactive } from 'vue'
import { flushPromises, mount } from '@vue/test-utils'
import AccountOpsView from '../AccountOpsView.vue'
import { useAppStore } from '@/stores/app'
import { getAccountOpsSettings, getAccountOpsEvents, getAccountOpsThresholdAccounts, saveAccountOpsNotificationSettings, saveAccountOpsRule, testAccountOpsWebhook } from '@/api/admin/accountOps'
const state = vi.hoisted(() => ({ auth: null as any }))
vi.mock('@/stores/auth', () => ({ useAuthStore: () => state.auth }))
vi.mock('@/components/layout/AppLayout.vue', () => ({ default: { template: '<main><slot /></main>' } }))
vi.mock('@/components/admin/operations/SmartOpsNav.vue', () => ({ default: { template: '<nav />' } }))
vi.mock('vue-i18n', async importOriginal => ({ ...await importOriginal<typeof import('vue-i18n')>(), useI18n: () => ({ t: (key: string) => key }) }))
vi.mock('@/api/admin/accountOps', () => ({ getAccountOpsSettings: vi.fn(), getAccountOpsEvents: vi.fn(), getAccountOpsThresholdAccounts: vi.fn(), saveAccountOpsNotificationSettings: vi.fn(), saveAccountOpsRule: vi.fn(), deleteAccountOpsRule: vi.fn(), saveAccountOpsWebhook: vi.fn(), deleteAccountOpsWebhook: vi.fn(), testAccountOpsWebhook: vi.fn() }))
const config = { enabled: false, recipient: '', balance_low: true, weekly_quota: true, cooldown_minutes: 60, webhooks: [], balance_thresholds: [], quota_thresholds: [] }
const settings = () => ({ config: { ...config }, smtp_configured: true, dropped_signals: 0, storage_failures: 0, encryption_key_configured: true })
const deferred = <T>() => { let resolve!: (value: T) => void; const promise = new Promise<T>(yes => { resolve = yes }); return { promise, resolve } }
const create = () => mount(AccountOpsView, { global: { plugins: [createPinia()], stubs: { teleport: true } } })
beforeEach(() => { vi.resetAllMocks(); state.auth = reactive({ user: { id: 1, role: 'admin' } }); vi.mocked(getAccountOpsSettings).mockResolvedValue(settings()); vi.mocked(getAccountOpsEvents).mockResolvedValue({ items: [], has_more: false }); vi.mocked(getAccountOpsThresholdAccounts).mockResolvedValue([]); vi.mocked(testAccountOpsWebhook).mockResolvedValue({ ok: true }); vi.mocked(saveAccountOpsNotificationSettings).mockImplementation(async c => ({ ...config, ...c })); vi.mocked(saveAccountOpsRule).mockResolvedValue(config) })
describe('account operations tabs and independent saves', () => {
  it('initializes a dynamically opened drawer from saved recovery-only flags', async () => {
    vi.mocked(getAccountOpsSettings).mockResolvedValue({ ...settings(), config: { ...config, balance_thresholds: [{ account_id: 1, enabled: true, threshold: 5, unit: 'USD', notify_alert: false, notify_recovery: true }] } } as any)
    vi.mocked(getAccountOpsThresholdAccounts).mockResolvedValue([{ account_id: 1, account_name: 'key', type: 'apikey', platform: 'openai', balance: 3, unit: 'USD', balance_status: 'ok', received_at: null, usage_windows: [] }])
    const wrapper = create(); await flushPromises()
    await wrapper.get('[data-testid="account-ops-tab-settings"]').trigger('click'); await flushPromises()
    await wrapper.get('[data-testid="edit-rule-1"]').trigger('click'); await flushPromises()
    expect((wrapper.get('[data-testid="rule-notify-alert"]').element as HTMLInputElement).checked).toBe(false)
    expect((wrapper.get('[data-testid="rule-threshold"]').element as HTMLInputElement).value).toBe('5')
    wrapper.unmount()
  })

  it('releases pagination when Refresh invalidates an in-flight page response', async () => {
    vi.mocked(getAccountOpsEvents).mockResolvedValue({ items: [], has_more: true })
    const wrapper = create(); await flushPromises()
    const old = deferred<{ items: []; has_more: boolean }>(); vi.mocked(getAccountOpsEvents).mockReturnValueOnce(old.promise)
    const page = (wrapper.vm as any).more()
    await (wrapper.vm as any).load()
    old.resolve({ items: [], has_more: false }); await page
    expect((wrapper.vm as any).loadingMore).toBe(false)
    wrapper.unmount()
  })

  it('opens records by default, with exactly two internal tabs and no settings form', async () => {
    const wrapper = create(); await flushPromises()
    const tabs = wrapper.findAll('[role="tab"]')
    expect(tabs).toHaveLength(2)
    expect(wrapper.get('[data-testid="account-ops-tab-records"]').attributes('aria-selected')).toBe('true')
    expect(wrapper.find('#account-ops-email').exists()).toBe(false)
    expect(getAccountOpsThresholdAccounts).not.toHaveBeenCalled()
    await wrapper.get('[data-testid="account-ops-tab-settings"]').trigger('click'); await flushPromises()
    expect(wrapper.get('[data-testid="account-ops-tab-settings"]').attributes('aria-selected')).toBe('true')
    expect(getAccountOpsThresholdAccounts).toHaveBeenCalledOnce()
    expect(wrapper.find('[data-testid="account-ops-channels"]').exists()).toBe(true)
    expect(wrapper.find('[data-testid="account-ops-rules"]').exists()).toBe(true)
    wrapper.unmount()
  })
  it('adds and removes an email channel without posting the global switch or failure rules', async () => {
    const wrapper = create(); await flushPromises()
    await wrapper.get('[data-testid="account-ops-tab-settings"]').trigger('click'); await flushPromises()
    expect(wrapper.find('[data-testid="account-ops-email-channel"]').exists()).toBe(false)
    await wrapper.get('[data-testid="account-ops-add-channel"]').trigger('click'); await flushPromises()
    await wrapper.get('[data-testid="add-channel-email"]').trigger('click'); await flushPromises()
    await wrapper.get('#account-ops-email').setValue('ops@example.com')
    await wrapper.get('#account-ops-email-form').trigger('submit'); await flushPromises()
    expect(saveAccountOpsNotificationSettings).toHaveBeenCalledWith({ recipient: 'ops@example.com' })
    expect(wrapper.find('#account-ops-email').exists()).toBe(false)
    expect(wrapper.get('[data-testid="account-ops-email-channel"]').text()).toContain('ops@example.com')
    await wrapper.get('[data-testid="delete-email-channel"]').trigger('click'); await flushPromises()
    expect(saveAccountOpsNotificationSettings).toHaveBeenLastCalledWith({ recipient: '' })
    expect(wrapper.find('[data-testid="account-ops-email-channel"]').exists()).toBe(false)
    wrapper.unmount()
  })
  it('keeps email addition available at the robot limit without an encryption key', async () => {
    vi.mocked(getAccountOpsSettings).mockResolvedValue({ ...settings(), encryption_key_configured: false, config: { ...config, webhooks: Array.from({ length: 5 }, (_, i) => ({ id: `bot-${i}`, provider: 'wecom' as const, enabled: true, url_configured: true })) } })
    const wrapper = create(); await flushPromises()
    await wrapper.get('[data-testid="account-ops-tab-settings"]').trigger('click'); await flushPromises()
    await wrapper.get('[data-testid="account-ops-add-channel"]').trigger('click'); await flushPromises()
    expect(wrapper.get('[data-testid="add-channel-email"]').attributes('disabled')).toBeUndefined()
    expect(wrapper.get('[data-testid="add-channel-feishu"]').attributes('disabled')).toBeDefined()
    await wrapper.get('[data-testid="add-channel-email"]').trigger('click'); await flushPromises()
    expect(wrapper.find('#account-ops-email').exists()).toBe(true)
    wrapper.unmount()
  })
  it('initializes a new robot from the platform chosen in Add channel', async () => {
    const wrapper = create(); await flushPromises()
    await wrapper.get('[data-testid="account-ops-tab-settings"]').trigger('click'); await flushPromises()
    await wrapper.get('[data-testid="account-ops-add-channel"]').trigger('click'); await flushPromises()
    await wrapper.get('[data-testid="add-channel-feishu"]').trigger('click'); await flushPromises()
    expect((wrapper.get('[data-testid^="account-ops-webhook-provider-"]').element as HTMLSelectElement).value).toBe('feishu')
    expect(wrapper.find('[data-testid^="account-ops-webhook-secret-"]').exists()).toBe(true)
    wrapper.unmount()
  })
  it('saves the master switch directly and restores its state when saving fails', async () => {
    vi.mocked(saveAccountOpsNotificationSettings).mockRejectedValueOnce(new Error('offline'))
    const wrapper = create(); await flushPromises()
    await wrapper.get('[data-testid="account-ops-tab-settings"]').trigger('click'); await flushPromises()
    expect(wrapper.find('[data-testid="edit-notification-settings"]').exists()).toBe(false)
    const toggle = wrapper.get('[data-testid="notifications-enabled"]')
    await toggle.trigger('click'); await flushPromises()
    expect(saveAccountOpsNotificationSettings).toHaveBeenLastCalledWith({ enabled: true })
    expect(toggle.attributes('aria-checked')).toBe('false')
    expect(useAppStore().toasts.at(-1)).toMatchObject({ type: 'error' })
    expect(wrapper.find('[role="alert"]').exists()).toBe(false)
    await toggle.trigger('click'); await flushPromises()
    expect(toggle.attributes('aria-checked')).toBe('true')
    expect(useAppStore().toasts.at(-1)).toMatchObject({ type: 'success' })
    expect(wrapper.text()).not.toContain('qualityOps.saved')
    wrapper.unmount()
  })
  it('keeps unsaved global rules during refresh and saves without affecting channels', async () => {
    vi.mocked(saveAccountOpsNotificationSettings).mockRejectedValueOnce(new Error('offline'))
    const wrapper = create(); await flushPromises()
    await wrapper.get('[data-testid="account-ops-tab-settings"]').trigger('click'); await flushPromises()
    await wrapper.get('[data-testid="notifications-enabled"]').trigger('click'); await flushPromises()
    expect(useAppStore().toasts.at(-1)).toMatchObject({ type: 'error' })
    const rules = wrapper.get('[data-testid="account-ops-rules"]')
    await rules.get('[data-testid="global-balance-low"]').setValue(false)
    await rules.get('[data-testid="global-cooldown"]').setValue(30)
    await (wrapper.vm as any).load(); await flushPromises()
    expect((rules.get('[data-testid="global-cooldown"]').element as HTMLInputElement).value).toBe('30')
    await rules.get('#account-ops-global-form').trigger('submit'); await flushPromises()
    expect(saveAccountOpsNotificationSettings).toHaveBeenLastCalledWith({ balance_low: false, weekly_quota: true, cooldown_minutes: 30 })
    expect(useAppStore().toasts.at(-1)).toMatchObject({ type: 'success' })
    expect(wrapper.find('[role="alert"]').exists()).toBe(false)
    expect(wrapper.find('[role="dialog"]').exists()).toBe(false)
    wrapper.unmount()
  })
  it('opens a rule drawer with amount and two independent notification switches', async () => {
    vi.mocked(getAccountOpsThresholdAccounts).mockResolvedValue([{ account_id: 1, account_name: 'key', type: 'apikey', platform: 'openai', balance: 3, unit: 'USD', balance_status: 'ok', received_at: null, usage_windows: [] }])
    const wrapper = create(); await flushPromises()
    await wrapper.get('[data-testid="account-ops-tab-settings"]').trigger('click'); await flushPromises()
    await wrapper.get('[data-testid="edit-rule-1"]').trigger('click'); await flushPromises()
    await wrapper.get('[data-testid="rule-threshold"]').setValue('5')
    await wrapper.get('[data-testid="rule-notify-alert"]').setValue(false)
    await wrapper.get('#account-ops-rule-form').trigger('submit'); await flushPromises()
    expect(saveAccountOpsRule).toHaveBeenCalledWith(1, { metric: 'balance', enabled: true, threshold: 5, unit: 'USD', notify_alert: false, notify_recovery: true })
    wrapper.unmount()
  })
  it('renders alert and recovery as different historical rows', async () => {
    const base = { account_id: 1, account_name: 'key', kind: 'balance_threshold' as const, signal: 'balance_threshold', http_status: 0, first_seen: '2026-10-07T12:00:00Z', last_seen: '2026-10-07T12:00:00Z', occurrences: 1, state: 'sent' as const, last_sent_at: '2026-10-07T12:00:00Z', next_send_at: '', attempts: 1 }
    vi.mocked(getAccountOpsEvents).mockResolvedValue({ items: [{ ...base, id: '1', phase: 'alert' }, { ...base, id: '2', phase: 'recovery' }], has_more: false })
    const wrapper = create(); await flushPromises()
    expect(wrapper.findAll('[data-testid="notification-record"]')).toHaveLength(2)
    expect(wrapper.text()).toContain('accountOps.phases.alert')
    expect(wrapper.text()).toContain('accountOps.phases.recovery')
    wrapper.unmount()
  })
  it('ignores a stale configuration response after a scoped save', async () => {
    const wrapper = create(); await flushPromises()
    const old = deferred<any>(); vi.mocked(getAccountOpsSettings).mockReturnValueOnce(old.promise)
    const refresh = (wrapper.vm as any).load()
    ;(wrapper.vm as any).acceptConfig({ ...config, recipient: 'new@example.com' })
    old.resolve(settings()); await refresh
    expect((wrapper.vm as any).remote.config.recipient).toBe('new@example.com')
    wrapper.unmount()
  })
  it('does not restore old admin configuration after logout', async () => {
    const old = deferred<any>(); vi.mocked(getAccountOpsSettings).mockReturnValueOnce(old.promise)
    const wrapper = create(); state.auth.user = null; old.resolve(settings()); await flushPromises()
    expect(wrapper.find('[data-testid="account-ops-rules"]').exists()).toBe(false)
    expect(wrapper.find('#account-ops-email').exists()).toBe(false)
    wrapper.unmount()
  })
})
