export type CodexQuickConfigPlatform =
  | 'openai'
  | 'anthropic'
  | 'gemini'
  | 'antigravity'
  | 'grok'
  | 'kimi'
  | 'zhipu'
  | 'deepseek'
  | 'minimax'
  | 'opencode_go'
  | 'composite'

export interface CodexQuickConfigInput {
  apiKey: string
  baseUrl: string
  platform?: CodexQuickConfigPlatform | null
  modelCatalogContent?: string
  modelCatalogPath?: string
}

const preferredModels: Record<CodexQuickConfigPlatform, string> = {
  openai: 'gpt-5.5',
  anthropic: 'claude-sonnet-4-6',
  gemini: 'gemini-2.5-pro',
  antigravity: 'claude-sonnet-4-6',
  grok: 'grok-4.5',
  kimi: 'kimi-k2.5',
  zhipu: 'glm-4.7',
  deepseek: 'deepseek-v4-pro',
  minimax: 'MiniMax-M3',
  opencode_go: 'glm-5.3',
  composite: 'gpt-5.5'
}

const providerNames: Record<CodexQuickConfigPlatform, string> = {
  openai: 'OpenAI',
  anthropic: 'Sub2API Anthropic',
  gemini: 'Sub2API Gemini',
  antigravity: 'Sub2API Antigravity',
  grok: 'Sub2API Grok',
  kimi: 'Sub2API Kimi',
  zhipu: 'Sub2API Zhipu',
  deepseek: 'Sub2API DeepSeek',
  minimax: 'Sub2API MiniMax',
  opencode_go: 'Sub2API OpenCode',
  composite: 'Sub2API Composite'
}

function escapeTomlBasicString(value: string): string {
  return value
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\r/g, '\\r')
    .replace(/\n/g, '\\n')
}

export function normalizeCodexBaseUrl(baseUrl: string): string {
  const trimmed = baseUrl.trim().replace(/\/+$/, '')
  if (!trimmed) return ''
  return /\/v1$/i.test(trimmed) ? trimmed : `${trimmed}/v1`
}

export function encodeUtf8Base64(value: string): string {
  const bytes = new TextEncoder().encode(value)
  let binary = ''
  for (const byte of bytes) binary += String.fromCharCode(byte)
  return btoa(binary)
}

export function buildCodexQuickConfigToml(input: CodexQuickConfigInput): string {
  const platform = input.platform || 'openai'
  const model = preferredModels[platform] || preferredModels.openai
  const provider = platform === 'openai' ? 'OpenAI' : 'sub2api'
  const providerName = providerNames[platform] || 'Sub2API'
  const catalogLine = input.modelCatalogContent
    ? `model_catalog_json = "${escapeTomlBasicString(input.modelCatalogPath || '~/.codex/codex-models.json')}"\n`
    : ''

  return `# Generated by Sub2API. Re-running the setup script replaces this file.
model_provider = "${provider}"
model = "${escapeTomlBasicString(model)}"
review_model = "${escapeTomlBasicString(model)}"
disable_response_storage = true
network_access = "enabled"
windows_wsl_setup_acknowledged = true
${catalogLine}
[model_providers.${provider}]
name = "${escapeTomlBasicString(providerName)}"
base_url = "${escapeTomlBasicString(normalizeCodexBaseUrl(input.baseUrl))}"
wire_api = "responses"
requires_openai_auth = false
experimental_bearer_token = "${escapeTomlBasicString(input.apiKey)}"
http_headers = { "x-openai-actor-authorization" = "local-image-extension" }
supports_websockets = false

[features]
goals = true
`
}

export function buildMacLinuxCodexQuickConfigScript(input: CodexQuickConfigInput): string {
  const configPayload = encodeUtf8Base64(buildCodexQuickConfigToml(input))
  const catalogPayload = input.modelCatalogContent ? encodeUtf8Base64(input.modelCatalogContent) : ''
  const catalogBlock = catalogPayload
    ? `CATALOG_PAYLOAD='${catalogPayload}'
CATALOG_TMP_FILE="$(mktemp "${'${CONFIG_FILE}'}.catalog.tmp.XXXXXX")"
if printf '%s' "${'${CATALOG_PAYLOAD}'}" | base64 --decode > "${'${CATALOG_TMP_FILE}'}" 2>/dev/null; then
  :
else
  printf '%s' "${'${CATALOG_PAYLOAD}'}" | base64 -D > "${'${CATALOG_TMP_FILE}'}"
fi
mv -f "${'${CATALOG_TMP_FILE}'}" "${'${CONFIG_DIR}'}/codex-models.json"
`
    : ''

  return `#!/usr/bin/env bash
set -euo pipefail

CONFIG_DIR="${'${HOME}'}/.codex"
CONFIG_FILE="${'${CONFIG_DIR}'}/config.toml"
mkdir -p "${'${CONFIG_DIR}'}"
TMP_FILE="$(mktemp "${'${CONFIG_FILE}'}.tmp.XXXXXX")"
trap 'rm -f "${'${TMP_FILE}'}" "${'${CATALOG_TMP_FILE:-}'}"' EXIT

PAYLOAD='${configPayload}'
if printf '%s' "${'${PAYLOAD}'}" | base64 --decode > "${'${TMP_FILE}'}" 2>/dev/null; then
  :
else
  printf '%s' "${'${PAYLOAD}'}" | base64 -D > "${'${TMP_FILE}'}"
fi

${catalogBlock}mv -f "${'${TMP_FILE}'}" "${'${CONFIG_FILE}'}"
trap - EXIT
printf 'Codex 配置成功。\\n'
printf '配置文件：%s\\n' "${'${CONFIG_FILE}'}"
printf '请重启 Codex 以加载新配置。\\n'
`
}

export function buildWindowsCmdCodexQuickConfigScript(input: CodexQuickConfigInput): string {
  const configPayload = encodeUtf8Base64(buildCodexQuickConfigToml(input))
  const catalogPayload = input.modelCatalogContent ? encodeUtf8Base64(input.modelCatalogContent) : ''
  const chunks = catalogPayload.match(/.{1,2000}/g) || []
  const catalogBlock = catalogPayload
    ? `set "SUB2API_CODEX_CATALOG_TEMP=%CONFIG_FILE%.catalog.tmp.%RANDOM%%RANDOM%"
> "%SUB2API_CODEX_CATALOG_TEMP%" echo ${chunks[0]}
${chunks.slice(1).map((chunk) => `>> "%SUB2API_CODEX_CATALOG_TEMP%" echo ${chunk}`).join('\n')}
if errorlevel 1 goto :error
powershell.exe -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command "$value = [IO.File]::ReadAllText($env:SUB2API_CODEX_CATALOG_TEMP); [IO.File]::WriteAllBytes($env:SUB2API_CODEX_CATALOG_TEMP, [Convert]::FromBase64String($value))"
if errorlevel 1 goto :error
move /Y "%SUB2API_CODEX_CATALOG_TEMP%" "%CONFIG_DIR%\\codex-models.json" >nul
if errorlevel 1 goto :error
`
    : ''

  return `@echo off
setlocal EnableExtensions DisableDelayedExpansion
chcp 65001 >nul

set "CONFIG_DIR=%USERPROFILE%\\.codex"
set "CONFIG_FILE=%CONFIG_DIR%\\config.toml"
set "TEMP_FILE=%CONFIG_FILE%.tmp.%RANDOM%%RANDOM%"
set "SUB2API_CODEX_PAYLOAD=${configPayload}"
set "SUB2API_CODEX_TEMP=%TEMP_FILE%"
set "SUB2API_CODEX_CATALOG_TEMP="

if not exist "%CONFIG_DIR%\\" mkdir "%CONFIG_DIR%" >nul 2>&1
if errorlevel 1 goto :error

${catalogBlock}powershell.exe -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command "$bytes = [Convert]::FromBase64String($env:SUB2API_CODEX_PAYLOAD); [IO.File]::WriteAllBytes($env:SUB2API_CODEX_TEMP, $bytes)"
if errorlevel 1 goto :error
move /Y "%TEMP_FILE%" "%CONFIG_FILE%" >nul
if errorlevel 1 goto :error

echo.
echo Codex 配置成功。
echo 配置文件："%CONFIG_FILE%"
echo 请重启 Codex 以加载新配置。
echo.
pause
exit /b 0

:error
del /q "%TEMP_FILE%" >nul 2>&1
if defined SUB2API_CODEX_CATALOG_TEMP del /q "%SUB2API_CODEX_CATALOG_TEMP%" >nul 2>&1
echo Codex 配置失败。 1>&2
pause
exit /b 1
`
}
